---
title: "hw6_Gayeon Park"
format: html
output-file: "index"
---

## **Excercise 1**

a.  What is the most interesting lesson, guide, or piece of advice Tufte offers you in this chapter?

    The most interesting guide would be space-time-story graphic which is ingeniously mixes space and time on the horizontal axis. The way the vertical and horizontal axes are established and the relationship between them is particularly compelling. Moreover, because the graphic uses high-quality illustrations, audiences can easily analyze the data and understand the message being conveyed. I didn't think about that way to express the graphic.

b.  Tufte shares some of his favorite graphics in this chapter. Pick one (but not the one about the military advance on and retreat from Russia) and answer the following.

-   What page is your graphic on? \[Take a screen shot and include the image as well, if you can.\]

    -   P.23

-   Why did you pick the graphic you chose?

    -   I'm interested in data map, especially historical world map. Through this graphic, we can see how early cartographers visualized global patterns such as winds and ocean currents.

-   What encoding channels are used in the graphic? What variables are they associated with?

    -   Position (X,Y) - latitude and longitude grid

    -   Line direction (including curve) - shows wind or current ocean direction.

    -   Symbols - circle or compass mark(?)

    -   Text labels - represents name of ocean and regions.

-   What, if any, elements of the graphic would be hard/impossible for you to implement in Vega-Lite (given what we know so far)?

    -   The most impossible implement thing would be decorating cartographic styling like above graphic. Also, drawing each single line (symbolize wind direction) might hard to implement.

-   What point is Tufte illustrating with this graphic?

    -   The graphic illustrates high data of density and layering each variables in one frame that it shows how multiple variables can be integrated without overwhelming the viewer.

## **Excercise 3**

-   There are two different Y-axis in one graphic \>\>\> concatenation

-   The position of text label \>\>\> using "dx" and "dy" to move the label position

-   The position of circle dot in each response rate (It is not center) \>\>\> using "type": "point" to match a center.

```{r}
library(vegawidget)
' 
{
  "$schema": "https://vega.github.io/schema/vega-lite/v6.json",
  "data":
    { "values" :
        [{"Date":"Q1-2017","Completion Rate":0.91,"Response Rate":0.023},
        {"Date":"Q2-2017","Completion Rate":0.93,"Response Rate":0.018},
        {"Date":"Q3-2017","Completion Rate":0.91,"Response Rate":0.028},
        {"Date":"Q4-2017","Completion Rate":0.89,"Response Rate":0.023},
        {"Date":"Q1-2018","Completion Rate":0.84,"Response Rate":0.034},
        {"Date":"Q2-2018","Completion Rate":0.88,"Response Rate":0.027},
        {"Date":"Q3-2018","Completion Rate":0.91,"Response Rate":0.026},
        {"Date":"Q4-2018","Completion Rate":0.87,"Response Rate":0.039},
        {"Date":"Q1-2019","Completion Rate":0.83,"Response Rate":0.028}] 
    },   
"columns": 2,
"concat": [
  {
    "title": "Completion Rates",
    "width": 300,
    "encoding": {
      "x": {"field": "Date", "type": "ordinal", "sort": null, "axis": {"labelAngle": 30}},
      "y": {"field": "Completion Rate", "type": "quantitative"}
    },
    "layer": [
      {"mark": {"type": "bar"}},
      {
      "mark": {"type": "text", "dx": -10, "color": "steelblue", "align": "left", "dy": -5},
      "encoding": {"text": {"field": "Completion Rate"}}}
    ]
  },
  {
    "title": "Response Rates",
    "width": 300,
    "encoding": {
      "x": {"field": "Date", "type": "ordinal", "sort": null,"axis": {"labelAngle": 30}},
      "y": {"field": "Response Rate", "type":"quantitative"}
    },
     "layer": [
      {"mark": {"type": "point"}},
      {"mark": {"type": "line"}},
      {
      "mark": {"type": "text", "dx": 5, "color": "steelblue", "align": "left"},
      "encoding": {"text": {"field": "Response Rate"}}}
    ]
  }
]
}

' |> as_vegaspec()
```
